### ISSUE TITLE
visual alignment (purely aesthetic)

### ISSUE THREAD

**Issue by antiochp** [j01tz/slatepack#2]
The armor prefix `BEGIN SLATEPACK.` is a single character too long to wrap nicely with the 15 char blocks.

```
BEGIN SLATEPACK. 2A4ijPMavuaBrAX EqsdWEtB5dy5ZN6 
H9md6GTf7GbsrPf c4i9i1atSdCknwQ 6nCcmJKmuUgkiu9 
KU5wFwUMYrZKXvV Z2TUVBbDwRYrS2L mA3ppP7o5EQ7yqR
```

`BEGIN SLATEPACK SIGNED MESSAGE.` fits nicely relative to a pair of 15 char blocks - 

```
BEGIN SLATEPACK SIGNED MESSAGE. 2A4ijPMavuaBrAX 
EqsdWEtB5dy5ZN6 H9md6GTf7GbsrPf c4i9i1atSdCknwQ 
6nCcmJKmuUgkiu9 KU5wFwUMYrZKXvV Z2TUVBbDwRYrS2L
```

`BEGIN SLATPACK.` would also work but maybe a little too close to `SALTPACK` and looks weird...

**Comment by j01tz** [comment]
Thanks, @antiochp it would have been much nicer if the message framing was the same length as words. 

One aspect worth considering is if we want to encode any more human readable data in these messages to help distinguish them. I've been considering `BEGIN SLATEPACK INITIAL`, `BEGIN SLATEPACK RESPONSE`, `BEGIN SLATEPACK 1/2` (for extremely long edge case slates), `BEGIN ENCRYPTED SLATEPACK`. All of these could be encoded underneath the human readable armor but it might be nice to have that data visible. Do you have any thoughts on this approach? Or does it seem cleaner to leave that data as machine readable only? This is where the armoring and serialization overlap a bit.

I do think it can make sense to do some optimizing here for human readability here because a few bytes won't make a major difference and are worth an improved user experience.

**Comment by lehnberg** [comment]
+1 for this, I coincidentally noticed/thought about the same mis-alignment when I pasted a slate into [grinnews](https://grinnews.substack.com/p/93-armored-slates-) just now!

**Comment by j01tz** [comment]
What about something like
```
BEGINSLATEPACK. 2xfX9bS82gxJ6jN
D6X4X843wrT84DT FkstYawTtacDqeU
MyGqBauGHxEFZNg FeEbVFsqXaKkKwK
tDvEwUBsuhb9GRf 1MK3jegnbKG5JJr
pbY4nbeZgPtRaZj QZL61Wj7iGqKBuJ
axfussSBrZq7xMQ P1rbw3GpebXkMeY
eXHDN9iascu. ENDSLATEPACK.
```
From my testing on mobile it looks like the words get split up into pairs to be displayed. I don't think we want to go larger than 15 character words or this gets jumbled a bit.

We also don't do any padding so the last word could be one or fifteen characters.

**Comment by j01tz** [comment]
I went ahead and merged https://github.com/j01tz/slatepack/pull/3 to try a more aligned framing based on feedback. Will keep this issue open in case we want to revisit other options here.

**Comment by antiochp** [comment]
Yes. Thanks! I like this - 

```
BEGINSLATEPACK. 2xfX9bS82gxJ6jN
D6X4X843wrT84DT FkstYawTtacDqeU
MyGqBauGHxEFZNg FeEbVFsqXaKkKwK
tDvEwUBsuhb9GRf 1MK3jegnbKG5JJr
pbY4nbeZgPtRaZj QZL61Wj7iGqKBuJ
axfussSBrZq7xMQ P1rbw3GpebXkMeY
eXHDN9iascu. ENDSLATEPACK.
```

**Comment by antiochp** [comment]
I think we should only have a single kind of armor as well, and not a specific version for each round of communication. I suspect that will blur the purpose of this.

I'd argue the payload should effectively be opaque within the armor.

**Comment by j01tz** [comment]
>I think we should only have a single kind of armor as well, and not a specific version for each round of communication.

I think this is where I am too after seeking more feedback. Going to close this now, thanks!
